title: "Jordan Terry"
description: ""
baseurl: ""
url: "https://jordanterry.co.uk"
google_analytics: 'G-B5WY7FZCS8'

# Social Media
github_username: jordanterry

# Theming
theme: minima
minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jordan-terry/" }
    - { platform: mastodon, user_url: "https://androiddev.social/@jordan_terry" }
    - { platform: github,  user_url: "https://github.com/jordanterry" }

include: 
  - .well-known

markdown: kramdown
paginate: 10
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
